import asyncio
from abc import ABC, abstractmethod
from collections.abc import Callable
from dataclasses import dataclass

from dynaflow.matching import MatchingRule


@dataclass
class InputInfo:
    """Summarized input characteristics for scheduling decisions.

    Attributes:
        batch_size: Number of requests in the batch.
        num_tokens: Per-request token counts.
        total_num_tokens: Sum of all tokens in the batch.
    """

    batch_size: int
    num_tokens: list[int]
    total_num_tokens: int


@dataclass
class SplitConfig:
    """Configuration for nano-batch splitting."""

    num_nano_batches: int
    """Number of nano-batches to split the batch into."""
    batch_sizes: list[int]
    """Sizes of each nano-batch. Length: num_nano_batches."""
    batch_indices: list[int]
    """Indices of the start and end of each nano-batch.
    Length: num_nano_batches + 1."""
    num_tokens: list[int]
    """Number of tokens in each nano-batch. Length: num_nano_batches."""
    num_tokens_padded: list[int]
    """Number of tokens in each nano-batch after padding.
    Length: num_nano_batches."""
    split_indices: list[int]
    """Indices of the start and end of each nano-batch.
    Length: num_nano_batches + 1."""
    is_dryrun: bool
    """Whether this is a dry run."""
    use_cudagraph: bool
    """Whether to use CUDA graph."""
    allow_fallback: bool = True
    """Allow fast-path fallback for single nano-batch execution.
    When True (default), single nano-batch bypasses the scheduler and
    runs the graph module directly.  Set to False to force
    scheduler-driven execution (e.g. when the scheduler substitutes
    ops via custom funcs)."""


@dataclass(eq=False, frozen=True)
class OperatorHandle:
    """Opaque identifier for a schedulable subgraph operator instance.

    Attributes:
        module_name: Name of the FX submodule corresponding to the operator.
        batch_idx: Batch index that this operator belongs to.
        batch_size: Number of tokens in the operator's batch.
        tag: A set of tags describing operator properties (e.g., "network").
    """

    module_name: str
    batch_idx: int
    batch_size: int
    tag: set[str]
    
    # Below are attributes for execution backend
    _is_dryrun: bool
    _use_cudagraph: bool


class ExecutionContext:
    """Context passed to the scheduler.

    Provides access to the split config, a pop() interface to receive ready
    operators from the engine, and an execute() API to request execution of
    one or more operators, optionally via a custom function.
    """

    def __init__(
        self,
        split_config: SplitConfig,
        op_queue: dict[int, asyncio.Queue[OperatorHandle]],
        execute_queue: asyncio.Queue[
            tuple[
                OperatorHandle | tuple[OperatorHandle],
                Callable | None,
                asyncio.Event,
            ]
        ],
    ) -> None:
        """Initialize the execution context.

        Args:
            split_config: The split configuration generated by the scheduler.
            op_queue: The queue to receive the ready operators from the engine.
            execute_queue: The queue to send execution requests to the engine.
        """
        self._split_config = split_config
        self._op_queue = op_queue
        self._execute_queue = execute_queue

    @property
    def split_config(self) -> SplitConfig:
        return self._split_config

    async def pop(self, batch_idx: int) -> OperatorHandle:
        """Wait for and return the next ready operator for a nano-batch."""
        return await self._op_queue[batch_idx].get()

    async def execute(
        self,
        operator: OperatorHandle | tuple[OperatorHandle],
        func: Callable | None = None,
    ) -> None:
        """Request execution of one or multiple operators.

        If `func` is provided, it will be called by the engine with materialized
        inputs for the specified operators, allowing grouped execution.
        """
        done_event = asyncio.Event()
        await self._execute_queue.put((operator, func, done_event))
        await done_event.wait()


class OpSchedulerBase(ABC):
    def __init__(self, policy_name: str | None = None) -> None:
        self.policy_name = policy_name

    @abstractmethod
    def get_split_rules(self) -> list[MatchingRule]:
        """Return a list of SplitRule describing cut-around intervals."""
        pass

    @abstractmethod
    def get_tag_rules(self) -> dict[MatchingRule, set[str]]:
        """Return a mapping from op name to tag set for backend decisions."""
        pass

    @abstractmethod
    def get_split_config(
        self,
        input_info: InputInfo,
        use_cudagraph: bool,
    ) -> SplitConfig:
        """Compute a policy-driven `SplitConfig` for the upcoming forward."""
        pass

    @abstractmethod
    async def schedule(self, context: ExecutionContext) -> None:
        """Drive execution by selecting ready operators and issuing requests."""
        pass


